### ISSUE TITLE
Something wrong with branch_for_base call (CircleCI)

### ISSUE THREAD

**Issue by ghost** [wojteklu/danger-mention#8]
## Log

```
bundle exec danger

[!] The exception involves the following plugins:
 -  danger-mention

bundler: failed to load command: danger (/home/ubuntu/repo/vendor/bundle/ruby/2.2.0/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: undefined method `branch_for_base' for #<Danger::Dangerfile:0x007f70336cc848>
 #  from Dangerfile:36
 #  -------------------------------------------
 #  # Mention potential reviewers
 >  mention.run
 #  -------------------------------------------

  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.0.5/lib/danger/danger_core/dangerfile.rb:68:in `method_missing'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.0.5/lib/danger/plugin_support/plugin.rb:23:in `method_missing'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-mention-0.4.0/lib/danger_plugin.rb:78:in `compose_urls'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-mention-0.4.0/lib/danger_plugin.rb:45:in `run'
  Dangerfile:36:in `block in parse'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.0.5/lib/danger/danger_core/dangerfile.rb:199:in `eval'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.0.5/lib/danger/danger_core/dangerfile.rb:199:in `block in parse'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.0.5/lib/danger/danger_core/dangerfile.rb:195:in `instance_eval'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.0.5/lib/danger/danger_core/dangerfile.rb:195:in `parse'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.0.5/lib/danger/danger_core/dangerfile.rb:272:in `run'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.0.5/lib/danger/danger_core/executor.rb:27:in `run'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.0.5/lib/danger/commands/runner.rb:66:in `run'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/gems/danger-4.0.5/bin/danger:5:in `<top (required)>'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/bin/danger:23:in `load'
  /home/ubuntu/repo/vendor/bundle/ruby/2.2.0/bin/danger:23:in `<top (required)>'

bundle exec danger returned exit code 1
```

## Dangerfile

```ruby
# Sometimes it's a README fix, or something like that - which isn't relevant for
# including in a project's CHANGELOG for example
# declared_trivial = github.pr_title.include? "#trivial"

# Make it more obvious that a PR is a work in progress and shouldn't be merged yet
warn("PR is classed as Work in Progress") if github.pr_title.include? "[WIP]"

# Warn when there is a big PR
warn("Big PR") if git.lines_of_code > 500

# Don't let testing shortcuts get into master by accident
# fail("fdescribe left in tests") if `grep -r fdescribe specs/ `.length > 1
# fail("fit left in tests") if `grep -r fit specs/ `.length > 1

# Ensure a PR has someone assigned to it
warn "This PR does not have any assignees yet." unless github.pr_json["assignee"]

# PRs should reference an issue
unless (github.pr_body.include? "Closes #" or github.pr_body.include? "Connects #")
  fail "This PR doesn't close or connect to an issue."
end

# PRs should almost always merge to dev.
unless github.branch_for_base == "dev"
  warn "This PR will not be merged into dev."
end

# Warn if TODOs are present in code
# todoist.warn_for_todos
# todoist.print_todos_table

# Lint commit message
commit_lint.check

# Mention potential reviewers
# mention.run
```

## Gemfile

```ruby
# frozen_string_literal: true
source "https://rubygems.org"

gem 'danger'
gem 'danger-todoist' # Checks for TODO etc in commits
gem 'danger-commit_lint' # Lints commit messages
gem 'danger-mention' # Mention potential reviewers
```

**Comment by sbalay** [comment]
I'm having the same issue. Here is the stacktrace from circleCi

```
bundle exec danger
[!] The exception involves the following plugins:
 -  danger-mention

bundler: failed to load command: danger (/opt/circleci/.rvm/gems/ruby-2.2.6/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: undefined method `branch_for_base' for #<Danger::Dangerfile:0x007f98ac972fd8>
 #  from Dangerfile:12
 #  -------------------------------------------
 #  # Mention possible reviewers
 >  mention.run(2, ["android/*", "ios/*"], [])
 #  -------------------------------------------

  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-4.1.0/lib/danger/danger_core/dangerfile.rb:68:in `method_missing'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-4.1.0/lib/danger/plugin_support/plugin.rb:23:in `method_missing'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-mention-0.4.0/lib/danger_plugin.rb:78:in `compose_urls'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-mention-0.4.0/lib/danger_plugin.rb:45:in `run'
  Dangerfile:12:in `block in parse'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-4.1.0/lib/danger/danger_core/dangerfile.rb:199:in `eval'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-4.1.0/lib/danger/danger_core/dangerfile.rb:199:in `block in parse'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-4.1.0/lib/danger/danger_core/dangerfile.rb:195:in `instance_eval'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-4.1.0/lib/danger/danger_core/dangerfile.rb:195:in `parse'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-4.1.0/lib/danger/danger_core/dangerfile.rb:272:in `run'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-4.1.0/lib/danger/danger_core/executor.rb:27:in `run'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-4.1.0/lib/danger/commands/runner.rb:66:in `run'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /opt/circleci/.rvm/gems/ruby-2.2.6/gems/danger-4.1.0/bin/danger:5:in `<top (required)>'
  /opt/circleci/.rvm/gems/ruby-2.2.6/bin/danger:23:in `load'
  /opt/circleci/.rvm/gems/ruby-2.2.6/bin/danger:23:in `<top (required)>'

bundle exec danger returned exit code 1
```

Dangerfile
```
# Sometimes it's a README fix, or something like that - which isn't relevant for
# including in a project's CHANGELOG for example
declared_trivial = github.pr_title.include? "#trivial"

# Make it more obvious that a PR is a work in progress and shouldn't be merged yet
warn("PR is classed as Work in Progress") if github.pr_title.include? "[WIP]"

# Warn when there is a big PR
warn("Big PR") if git.lines_of_code > 500

# Mention possible reviewers
mention.run(2, ["android/*", "ios/*"], [])
```

circle.yml
```
machine:
  node:
    version: 6
dependencies:
  override:
    - yarn
    - bundle
test:
  override:
    - npm test
    - npm run lint
    - bundle exec danger
```

**Comment by KrauseFx** [comment]
I can confirm running into the same issue on Circle for _fastlane_:

```
[!] The exception involves the following plugins:
 -  danger-mention

bundler: failed to load command: danger (/Users/distiller/.gem/ruby/2.3.1/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: undefined method `branch_for_base' for #<Danger::Dangerfile:0x007f9afbdb8358>
 #  from Dangerfile:36
 #  -------------------------------------------
 #  # Mention people who might be good reviewers for this code
 >  mention.run(2, [], ["KrauseFx"])
 #  -------------------------------------------
```

**Comment by orta** [comment]
This was fixed in https://github.com/danger/danger-mention/commit/96a4d63020df165f71ea0f7abeaf5eb3dd360817#diff-8779f9203f0e53486f80fde88b1552c9R78 - I'll try get a release out as soon as I get permission to push to rubygems 👍

**Comment by orta** [comment]
For now, in your gemfile use master with `gem "danger-mention", :github => "https://github.com/danger/danger-mention.git"`

**Comment by orta** [comment]
Fixed and deployed - thanks @wojteklu
